version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10.6"

formats:
  - pdf
  - htmlzip

python:
  version: 3.10.6
  install:
    - path: .
      extra_requirements:
        - docs/

sphinx:
  configuration: docs/conf.py
